# Custom keymap for yazi
[[mgr.prepend_keymap]]
  desc = "Jump to char"
  on   = "f"
  run  = "plugin jump-to-char"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["1"]
  run  = "plugin relative-motions 1"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["2"]
  run  = "plugin relative-motions 2"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["3"]
  run  = "plugin relative-motions 3"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["4"]
  run  = "plugin relative-motions 4"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["5"]
  run  = "plugin relative-motions 5"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["6"]
  run  = "plugin relative-motions 6"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["7"]
  run  = "plugin relative-motions 7"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["8"]
  run  = "plugin relative-motions 8"

[[mgr.prepend_keymap]]
  desc = "Move in relative steps"
  on   = ["9"]
  run  = "plugin relative-motions 9"
