keys:
  # users
  - &cny age1z9fpa8c4v4fmdu42myc6uyapvs9436tns9myss5yqv6p3cmrny2s4rs6kt
  - &spy age1kam6fzccmuq6mnsuk64mnhhw5937avqpl2xslj5v8feasrdsca8sra4p0z
  - &mca age1072nv5djq53dz279ayhpm2lcmk7w7k28mpqpsqqxuszxtvdlayys9l5n4m
  # hosts
creation_rules:
  - path_regex: ^secrets/shared/.*\.yaml$
    key_groups:
      - age:
          - *cny
  - path_regex: ^secrets/mbp/.*\.yaml$
    key_groups:
      - age:
          - *cny
  - path_regex: ^secrets/esquire/.*\.yaml$
    key_groups:
      - age:
          - *cny
          - *spy
  - path_regex: ^secrets/acerus/.*\.yaml$
    key_groups:
      - age:
          - *spy
          - *mca
