[language-server.typescript-language-server]
  args    = ["--stdio"]
  command = "typescript-language-server"

[[language]]
  file-types = ["js", "cjs", "mjs"]
  formatter = { command = "prettier", args = [
    "--stdin-filepath",
    "%val{buffer_name}",
  ] }
  indent = { tab-width = 2, unit = "  " }
  injection-regex = "javascript"
  language-servers = ["typescript-language-server"]
  name = "javascript"
  scope = "source.js"

[[language]]
  file-types = ["ts"]
  formatter = { command = "prettier", args = [
    "--stdin-filepath",
    "%val{buffer_name}",
  ] }
  indent = { tab-width = 2, unit = "  " }
  injection-regex = "typescript"
  language-servers = ["typescript-language-server"]
  name = "typescript"
  scope = "source.ts"
