# Status bar style 1
set -g status-left " session: #[fg=yellow,bold]#S "
set -g status-left-length 50    # increase length (from 10)
# set -g status-right "#[fg=white,nobold]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml)"
set -g status-right ""
set -g status-position top       # macOS / darwin style
set -g status-style 'bg=default' # transparent
set -g status-interval 1  # Refresh the status line every second

set -g window-status-format ' #[fg=gray]#I:#{?window_zoomed_flag,#W Z,#W}'
set -g window-status-current-format ' #[fg=yellow]#I:#{?window_zoomed_flag,#W Z,#W}'
