set -g status-position bottom
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"
set -g window-status-format ' #I:#W'
set -g window-status-current-format ' #I:#W'
set -g window-status-style "fg=#f5e0dc"
set -g window-status-current-style "fg=#f9e2af,bold"

# status left
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold]  #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}]  #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# status right
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{e|>=:10,#{battery_percentage}},#{#[bg=#{@thm_red},fg=#{@thm_bg}]},#{#[bg=#{@thm_bg},fg=#{@thm_pink}]}} #{battery_icon} #{battery_percentage} "
set -ga status-right "#{?window_zoomed_flag,#[fg=#{@thm_yellow}]  zoom ,}"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_blue}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# panes border
set -g pane-border-lines heavy
set -g pane-border-status bottom                    # Place pane status below.
set -g pane-border-format ""                       # Keep the title area empty.
set -g pane-border-style "fg=white"                # Normal pane border.
set -g pane-active-border-style "fg=green"         # Active pane border.
set -g display-panes-colour "black"
set -g display-panes-active-colour "white"
