# Status bar style 1
set -g status-left " #[fg=yellow,bold]#S "
set -g status-left-length 50    # increase length (from 10)
# set -g status-right "#[fg=white,nobold]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml)"
set -g status-right ""
set -g status-position bottom
set -g status-style 'bg=default' # transparent
set -g status-interval 1  # Refresh the status line every second

set -g window-status-format ' #[fg=gray]#I:#{?window_zoomed_flag,#W Z,#W}'
set -g window-status-current-format ' #[fg=yellow]#I:#{?window_zoomed_flag,#W Z,#W}'

# pane borders
set -g pane-border-lines double
set -g pane-border-status bottom                    # Place pane status below.
set -g pane-border-format ""                       # Keep the title area empty.
set -g pane-border-style "fg=white"                # Normal pane border.
set -g pane-active-border-style "fg=green"         # Active pane border.
set -g display-panes-colour "black"
set -g display-panes-active-colour "white"

set-hook -g 'after-new-session'  'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-new-window'   'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-kill-pane'    'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'pane-exited'        'run-shell -b "if [ \#{window_panes} -eq 1 ]; then tmux set pane-border-status off; fi"'
set-hook -g 'after-split-window' 'run-shell -b "if [ \#{window_panes} -gt 1 ]; then tmux set pane-border-status bottom; fi"'
