# Syntax highlighting
# -------------------
"attribute"                   = "yellow"
"comment"                     = { fg = "overlay2", modifiers = ["italic"] }
"constant"                    = "peach"
"constant.character"          = "teal"
"constant.character.escape"   = "pink"
"constructor"                 = "sapphire"
"diff.delta"                  = "blue"
"diff.minus"                  = "red"
"diff.plus"                   = "green"
"function"                    = "blue"
"function.macro"              = "rosewater"
"keyword"                     = "mauve"
"keyword.control.conditional" = { fg = "mauve", modifiers = ["italic"] }
"label"                       = "sapphire"                                            # used for lifetimes
"markup.bold"                 = { fg = "red", modifiers = ["bold"] }
"markup.heading.1"            = "red"
"markup.heading.2"            = "peach"
"markup.heading.3"            = "yellow"
"markup.heading.4"            = "green"
"markup.heading.5"            = "sapphire"
"markup.heading.6"            = "lavender"
"markup.italic"               = { fg = "red", modifiers = ["italic"] }
"markup.link.label"           = "sapphire"
"markup.link.text"            = "lavender"
"markup.link.url"             = { fg = "blue", modifiers = ["italic", "underlined"] }
"markup.list"                 = "teal"
"markup.list.checked"         = "green"
"markup.list.unchecked"       = "overlay2"
"markup.quote"                = "pink"
"markup.raw"                  = "green"
"namespace"                   = { fg = "yellow", modifiers = ["italic"] }
"operator"                    = "sky"
"punctuation"                 = "overlay2"
"punctuation.special"         = "sky"
"special"                     = "blue"                                                # fuzzy highlight
"string"                      = "green"
"string.regexp"               = "pink"
"string.special"              = "blue"
"string.special.symbol"       = "red"
"tag"                         = "blue"
"type"                        = "yellow"
"type.enum.variant"           = "teal"
"variable"                    = "text"
"variable.builtin"            = "red"
"variable.other.member"       = "blue"
"variable.parameter"          = { fg = "maroon", modifiers = ["italic"] }
# User Interface
# --------------
"diagnostic.error"         = { underline = { color = "red", style = "curl" } }
"diagnostic.hint"          = { underline = { color = "teal", style = "curl" } }
"diagnostic.info"          = { underline = { color = "sky", style = "curl" } }
"diagnostic.unnecessary"   = { modifiers = ["dim"] }
"diagnostic.warning"       = { underline = { color = "yellow", style = "curl" } }
error                      = "red"
hint                       = "teal"
info                       = "sky"
rainbow                    = ["red", "peach", "yellow", "green", "sapphire", "lavender"]
"ui.background"            = { fg = "text", bg = "base" }
"ui.bufferline"            = { fg = "subtext0", bg = "mantle" }
"ui.bufferline.active"     = { fg = "mauve", bg = "base", underline = { color = "mauve", style = "line" } }
"ui.bufferline.background" = { bg = "crust" }
"ui.cursor"                = { fg = "base", bg = "secondary_cursor" }
"ui.cursor.insert"         = { fg = "base", bg = "secondary_cursor_insert" }
"ui.cursor.match"          = { fg = "peach", modifiers = ["bold"] }
"ui.cursor.normal"         = { fg = "base", bg = "secondary_cursor_normal" }
"ui.cursor.primary"        = { fg = "base", bg = "rosewater" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.normal" = { fg = "base", bg = "rosewater" }
"ui.cursor.primary.select" = { fg = "base", bg = "lavender" }
"ui.cursor.select"         = { fg = "base", bg = "secondary_cursor_select" }
"ui.cursorline.primary"    = { bg = "cursorline" }
"ui.help"                  = { fg = "overlay2", bg = "surface0" }
"ui.highlight"             = { bg = "surface1", modifiers = ["bold"] }
"ui.linenr"                = { fg = "surface1" }
"ui.linenr.selected"       = { fg = "lavender" }
"ui.menu"                  = { fg = "overlay2", bg = "surface0" }
"ui.menu.selected"         = { fg = "text", bg = "surface1", modifiers = ["bold"] }
"ui.popup"                 = { fg = "text", bg = "surface0" }
"ui.selection"             = { bg = "surface1" }
"ui.statusline"            = { fg = "subtext1", bg = "mantle" }
"ui.statusline.inactive"   = { fg = "surface2", bg = "mantle" }
"ui.statusline.insert"     = { fg = "base", bg = "green", modifiers = ["bold"] }
"ui.statusline.normal"     = { fg = "base", bg = "rosewater", modifiers = ["bold"] }
"ui.statusline.select"     = { fg = "base", bg = "lavender", modifiers = ["bold"] }
"ui.text"                  = "text"
"ui.text.directory"        = { fg = "blue" }
"ui.text.focus"            = { fg = "text", bg = "surface0", modifiers = ["bold"] }
"ui.text.inactive"         = { fg = "overlay1" }
"ui.virtual"               = "overlay0"
"ui.virtual.indent-guide"  = "surface0"
"ui.virtual.inlay-hint"    = { fg = "surface1", bg = "mantle" }
"ui.virtual.jump-label"    = { fg = "rosewater", modifiers = ["bold"] }
"ui.virtual.ruler"         = { bg = "surface0" }
"ui.window"                = { fg = "crust" }
warning                    = "yellow"

[palette]
  base                    = "#1e1e2e"
  blue                    = "#89b4fa"
  crust                   = "#11111b"
  cursorline              = "#2a2b3c"
  flamingo                = "#f2cdcd"
  green                   = "#a6e3a1"
  lavender                = "#b4befe"
  mantle                  = "#181825"
  maroon                  = "#eba0ac"
  mauve                   = "#cba6f7"
  overlay0                = "#6c7086"
  overlay1                = "#7f849c"
  overlay2                = "#9399b2"
  peach                   = "#fab387"
  pink                    = "#f5c2e7"
  red                     = "#f38ba8"
  rosewater               = "#f5e0dc"
  sapphire                = "#74c7ec"
  secondary_cursor        = "#b5a6a8"
  secondary_cursor_insert = "#7ea87f"
  secondary_cursor_normal = "#b5a6a8"
  secondary_cursor_select = "#878ec0"
  sky                     = "#89dceb"
  subtext0                = "#a6adc8"
  subtext1                = "#bac2de"
  surface0                = "#313244"
  surface1                = "#45475a"
  surface2                = "#585b70"
  teal                    = "#94e2d5"
  text                    = "#cdd6f4"
  yellow                  = "#f9e2af"
