# === ENABLED PLUGINS ===
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'kristijan/flash-copy.tmux'

# === UNUSED PLUGINS ===
# set -g @plugin 'b0o/tmux-autoreload'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-cpu'
# set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'tmux-plugins/tmux-online-status'
# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
# set -g @plugin 'omerxx/tmux-sessionx'
# set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'navahas/tmux-grimoire' # https://github.com/navahas/tmux-grimoire
# set -g @plugin 'omerxx/tmux-floax' # Floating terminal window
# set -g @plugin 'tmux-plugins/tmux-net-speed'
# set -g @plugin 'kylepeeler/tmux-nightowl'

# === PLUGINS SETTINGS ===

# -> Custom config for tmux plugin 'omerxx/tmux-sessionx' <-
# I recommend using 'o' if not already in use, for least key strokes when launching
# set -g @sessionx-bind 'o'

# -> Custom config for tmux plugin 'tmux-resurrect' and 'tmux-continuum' <-
# set -g @resurrect-processes 'nvim' # the option for program can be reuserrected is LIMITED / https://github.com/tmux-plugins/tmux-resurrect/blob/master/docs/restoring_programs.md
# set -g @resurrect-processes-debug 'on' # Debugging resurrect
# set -g @continuum-restore 'on' # Auto restore when starting tmux without pressing <prefix>+<C+r>

# -> Custom config for tmux plugin 'catppuccin' <-
# set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded"
# # So when renaming a window, the renamed window name appears in the window's tab bar. This only relates to catppuccin's behavior
# set -g @catppuccin_window_default_text " #W"
# set -g @catppuccin_window_current_text " #W"
# set -g @catppuccin_window_text " #W"

# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.config/tmux/plugins/tmux/catppuccin.tmux`
