# === BASIC SETTINGS ===
# 'set' alias for 'set-option' and 'setw' alias for 'set-window-option'

# set -g default-shell /opt/homebrew/bin/fish
set -g mode-keys vi # Use vim style key bindings in copy-mode
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g renumber-windows on   # renumber all windows when any window is closed
set -g base-index 1 # Set base index for windows
set -g pane-base-index 1 # Set base index for panes
set -g mouse on # Enable mouse support
set -g default-terminal "tmux-256color" # 'xterm-256color' is widely used by terminal emulator but you can change to 'tmux-256color' is specifically designed for tmux and is optimized for use within tmux sessions.
# Preserve modifier keys such as Shift+Enter for applications inside tmux.
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features ',xterm-ghostty:extkeys'
set -as terminal-overrides ",*:Tc"
set -sg escape-time 0
set -g focus-events on
# set -ga terminal-overrides ",xterm-256color:Tc"
set -g allow-rename off # Allow programs in the pane to change the window name a terminal escape sequence (\ek...\e\\).
set -gq allow-passthrough on
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q' # set cursor style to back set by the terminal app
# set-option -g automatic-rename off # Control automatic window renaming. When this setting enabled, tmux will rename the window automatically the format specified by automatic-rename-format.

# --- Define colour scheme --- #
_tmux_white=colour15
_tmux_black=colour232
_tmux_red=colour1
_tmux_purple=colour54
_tmux_grey_l=colour145
_tmux_grey_d=colour236
_tmux_blue=colour5
_tmux_blue_d=colour17
_tmux_green=colour2
# ---------------------------- #

# Window naming
# The selected status bar style displays the zoomed-window indicator.
set -g automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"
