[metadata]
  description  = "Browse Git reflog entries"
  name         = "xgit-reflogs"
  requirements = ["git"]

[source]
  ansi     = true
  command  = "git reflog --format='%gD%x09%C(yellow)%h%C(auto) %gs%C(reset)' 2>/dev/null"
  frecency = false
  no_sort  = true
  output   = "{strip_ansi|split:\\t:0}"

[preview]
  command = "DFT_COLOR=always git show --ext-diff --color=always '{split:\\t:0}'"

[ui]
  layout = "landscape"

  [ui.preview_panel]
    size = 65

[actions.checkout-detached]
  command     = "git switch --detach '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Checkout reflog entry detached (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.cherry-pick]
  command     = "git cherry-pick '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Cherry-pick reflog entry (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.hard-reset]
  command     = "git reset --hard '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Hard-reset to reflog entry (destructive; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"
