[metadata]
  description  = "Browse Git commit hashes"
  name         = "xgit-hashes"
  requirements = ["git"]

[source]
  ansi     = true
  command  = "git log --date=short --color=always --format='%h%x09%C(green)%ad %C(auto)%h%d %s %C(blue)(%an)%C(reset)' 2>/dev/null"
  frecency = false
  no_sort  = true
  output   = "{strip_ansi|split:\\t:0}"

[preview]
  command = "DFT_COLOR=always git show --ext-diff --color=always '{split:\\t:0}'"

[ui]
  layout = "landscape"

  [ui.preview_panel]
    size = 65

[actions.open-browser]
  command     = "$HOME/.config/television/scripts/git-open commit '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Open commit in browser"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.diff-working-tree]
  command     = "git diff --color=always '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Diff commit against working tree"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.checkout-detached]
  command     = "git switch --detach '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Checkout commit detached (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.cherry-pick]
  command     = "git cherry-pick '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Cherry-pick commit (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.revert]
  command     = "git revert '{split:\\n:0|strip_ansi|split:\\t:0}'"
  description = "Revert commit (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"
