[metadata]
name = "xgit-hashes"
description = "Browse Git commit hashes"
requirements = ["git"]

[source]
command = "git log --date=short --color=always --format='%h%x09%C(green)%ad %C(auto)%h%d %s %C(blue)(%an)%C(reset)' 2>/dev/null"
ansi = true
no_sort = true
frecency = false
output = "{strip_ansi|split:\\t:0}"

[preview]
command = "DFT_COLOR=always git show --ext-diff --color=always '{split:\\t:0}'"

[ui]
layout = "landscape"

[ui.preview_panel]
size = 65

[actions.open-browser]
description = "Open commit in browser"
command = "$HOME/.config/television/scripts/git-open commit '{split:\\n:0|strip_ansi|split:\\t:0}'"
shell = "bash"
mode = "fork"
separator = "\n"

[actions.diff-working-tree]
description = "Diff commit against working tree"
command = "git diff --color=always '{split:\\n:0|strip_ansi|split:\\t:0}'"
shell = "bash"
mode = "fork"
separator = "\n"

[actions.checkout-detached]
description = "Checkout commit detached (modifies repository; Ctrl-R to reload)"
command = "git switch --detach '{split:\\n:0|strip_ansi|split:\\t:0}'"
shell = "bash"
mode = "fork"
separator = "\n"

[actions.cherry-pick]
description = "Cherry-pick commit (modifies repository; Ctrl-R to reload)"
command = "git cherry-pick '{split:\\n:0|strip_ansi|split:\\t:0}'"
shell = "bash"
mode = "fork"
separator = "\n"

[actions.revert]
description = "Revert commit (modifies repository; Ctrl-R to reload)"
command = "git revert '{split:\\n:0|strip_ansi|split:\\t:0}'"
shell = "bash"
mode = "fork"
separator = "\n"
