[metadata]
  description  = "Browse Git remotes"
  name         = "xgit-remotes"
  requirements = ["git"]

[source]
  command  = "git remote -v 2>/dev/null | sort | awk '{print $1 \"\\t\" $2}' | uniq"
  frecency = false
  no_sort  = true
  output   = "{split:\\t:0}"

[preview]
  command = "git log --oneline --graph --date=short --color=always --pretty=format:'%C(auto)%cd %h%d %s' --remotes='{split:\\t:0}' --"

[ui]
  layout = "landscape"

  [ui.preview_panel]
    size = 65

[actions.open-browser]
  command     = "$HOME/.config/television/scripts/git-open remote '{split:\\n:0|split:\\t:0}'"
  description = "Open remote in browser"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.fetch]
  command     = "git fetch '{split:\\n:0|split:\\t:0}'"
  description = "Fetch remote (modifies repository; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"

[actions.fetch-prune]
  command     = "git fetch --prune '{split:\\n:0|split:\\t:0}'"
  description = "Fetch and prune remote (destructive; Ctrl-R to reload)"
  mode        = "fork"
  separator   = "\n"
  shell       = "bash"
