[[session]]
  name = "Downloads 📥"
  path = "~/Downloads"
  # startup_command = "ls"

[[session]]
  name            = "backend"
  path            = "~/Code/Personal/Projects/Backend/allweezy-backend"
  startup_command = "nvim"
  windows         = ["opencode", "codex", "terminal"]

[[session]]
  name            = "dotfiles"
  path            = "~/.local/share/chezmoi"
  startup_command = "nvim"
  windows         = ["dotnix", "dot_config"]

[[window]]
  name           = "dotnix"
  path           = "~/Code/Personal/Experiments/nix-dendritic-projects/dotnix"
  startup_script = "nvim"

[[window]]
  name           = "dot_config"
  path           = "~/.config"
  startup_script = "nvim"

[[window]]
  name           = "opencode"
  startup_script = "opencode"

[[window]]
  name           = "monitoring"
  startup_script = "btop"

[[window]]
  name           = "codex"
  startup_script = "codex"

[[window]]
  name           = "terminal"
  startup_script = "doppler run -- bun run dev"
