# SUPER
# Layouts
bind=SUPER,n,switch_layout
bind=SUPER,t,setlayout,tile
bind=SUPER,s,setlayout,scroller

# Scratchpad
# send current window to scratchpad
bind=SUPER,i,minimized

# Window/App actions
bind=SUPER,Q,killclient
bindl=SUPER,L,spawn,swaylock
bind=SUPER,Return,spawn,ghostty
bind=SUPER,Z,spawn,zen-beta
bind=SUPER,X,spawn,firefox
bind=SUPER,Space,spawn,fuzzel

# Focus and window state
bind=SUPER,Tab,focusstack,next
bind=SUPER,g,toggleglobal
bind=SUPER,f,togglefullscreen
bind=SUPER,o,toggleoverlay

# Tag/view navigation
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,M,view,9,0

# SUPER+SHIFT
# Scratchpad
# retrieve window from scratchpad (restore)
bind=SUPER+SHIFT,i,restore_minimized

# Window actions
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,Q,togglefloating
bind=SUPER+SHIFT,f,togglefakefullscreen
# bind=SUPER+SHIFT,I,restore_minimized

# ALT
# Scratchpad
# toggle (show/hide) the scratchpad
bind=ALT,z,toggle_scratchpad

# Focus and overview
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down
bind=ALT,Tab,toggleoverview
bind=ALT,a,togglemaximizescreen

# CTRL
bind=CTRL,Left,viewtoleft_have_client,0
bind=CTRL,Right,viewtoright_have_client,0

# CTRL+SUPER
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

# Mouse Binding
# Window manipulation
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_right,killclient

# Overview mode (requires NONE modifier)
mousebind=SUPER+SHIFT,btn_left,toggleoverview,1
mousebind=SUPER+SHIFT,btn_right,killclient,0
mousebind=NONE,btn_middle,togglemaximizescreen,0

# Noctalia
bind = SUPER, A, spawn, noctalia-shell ipc call launcher toggle

# bind = SUPER, S, spawn, noctalia-shell ipc call controlCenter toggle
bind = SUPER, comma, spawn, noctalia-shell ipc call settings toggle

bind = SUPER, V, spawn, noctalia-shell ipc call launcher clipboard

bind = SUPER, L, spawn, noctalia-shell ipc call lockScreen lock

bind = SUPER, J, spawn, noctalia-shell ipc call bar toggle
bind = CTRL+SUPER, T, spawn, noctalia-shell ipc call wallpaper toggle
