bind=SUPER+SHIFT,r,reload_config

# SUPER
# Layouts
bind=SUPER,n,switch_layout
bind=SUPER,t,setlayout,tile
bind=SUPER,s,setlayout,scroller

# Scratchpad
# send current window to scratchpad
bind=SUPER,i,minimized

# Window/App actions
bind=SUPER,Q,killclient
bindl=SUPER,L,spawn,swaylock
bind=SUPER,Return,spawn,ghostty
bind=SUPER,Z,spawn,zen-beta
bind=SUPER,X,spawn,firefox
# bind=SUPER,Space,spawn,fuzzel

# Focus and window state
bind=SUPER,Tab,focusstack,next
bind=SUPER,g,toggleglobal
bind=SUPER,f,togglefullscreen
bind=SUPER,o,toggleoverlay

# === WINDOW KEYBIND ===
# Window Focus
bind=ALT,H,focusdir,left
bind=ALT,J,focusdir,down
bind=ALT,K,focusdir,up
bind=ALT,L,focusdir,right

# Move window to selected tag
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Move window in direction in the same tag
bind=ALT+SUPER,K,exchange_client,up
bind=ALT+SUPER,J,exchange_client,down
bind=ALT+SUPER,H,exchange_client,left
bind=ALT+SUPER,L,exchange_client,right

# Scratchpad minimized
bind=SUPER+SHIFT,i,restore_minimized

# Misc
bind=ALT+SUPER,Q,togglefloating
bind=ALT+SUPER,F,togglefakefullscreen
# toggle (show/hide) the scratchpad
bind=ALT,Z,toggle_scratchpad
bind=ALT,Tab,toggleoverview
bind=ALT,a,togglemaximizescreen

# Mouse Window manipulation
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER+CTRL,btn_right,killclient

# === TAG ===
# Switch between tag left / right that have window inside the tag
bind=CTRL,Left,viewtoleft_have_client,0
bind=CTRL,Right,viewtoright_have_client,0

# Tag/view navigation
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# Overview mode (requires NONE modifier)
mousebind=SUPER+SHIFT,btn_left,toggleoverview,1
mousebind=SUPER+SHIFT,btn_right,killclient,0
mousebind=NONE,btn_middle,togglemaximizescreen,0

# Noctalia
bind = SUPER, Space, spawn, noctalia-shell ipc call launcher toggle

# bind = SUPER, S, spawn, noctalia-shell ipc call controlCenter toggle
bind = SUPER, comma, spawn, noctalia-shell ipc call settings toggle

bind = SUPER, V, spawn, noctalia-shell ipc call launcher clipboard

bind = SUPER, L, spawn, noctalia-shell ipc call lockScreen lock

bind = SUPER, J, spawn, noctalia-shell ipc call bar toggle
bind = CTRL+SUPER, T, spawn, noctalia-shell ipc call wallpaper toggle
