# Layouts
bind=SUPER,n,switch_layout # cycle through layouts
# Set specific layout
bind=SUPER,t,setlayout,tile
bind=SUPER,s,setlayout,scroller

# Scratchpad
bind=SUPER,i,minimized # send current window to scratchpad
bind=ALT,z,toggle_scratchpad # toggle (show/hide) the scratchpad
bind=SUPER+SHIFT,i,restore_minimized # retrieve window from scratchpad (restore)


bind=SUPER,Q,killclient
bindl=SUPER,L,spawn,swaylock

# Apps
bind=SUPER,T,ghostty
bind=SUPER,Z,zen
bind=SUPER,X,firefox
