# keyboard
repeat_rate=40
repeat_delay=300
numlockon=1
xkb_rules_layout=us
# xkb_rules_options=caps:escape,ctrl:nocaps

# mouse
mouse_natural_scrolling=0
accel_profile=2
# move window by mouse
drag_tile_to_tile=1

# trackpad
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
disable_while_typing=0
scroll_method=1
click_method=2
send_events_mode=0
