# keyboard
repeat_rate=40
repeat_delay=300
numlockon=1
xkb_rules_layout=us
# xkb_rules_options=caps:escape,ctrl:nocaps

# mouse
mouse_natural_scrolling=0
accel_profile=2
# move window by mouse
drag_tile_to_tile=1
