# tag placement
windowrule=tags:1,appid:^(ghostty|com\\.mitchellh\\.ghostty)$
windowrule=tags:2,appid:^firefox$
windowrule=tags:3,appid:^(1[Pp]assword|com\\.1password\\.1password)$

# app behavior
windowrule=isterm:1,appid:^(ghostty|com\\.mitchellh\\.ghostty)$
# windowrule=force_maximize:1,appid:^firefox$
windowrule=isfloating:1,appid:^(1[Pp]assword|com\\.1password\\.1password)$

# Limit to specific monitor
tagrule=id:1,monitor_name:DP-5,layout_name:scroller
tagrule=id:2,monitor_name:DP-5,layout_name:scroller

# == Screenshot Tool ==
# No blur or animation for slurp selection layer (avoids occlusion and ghosting in screenshots)
layerrule=noanim:1,noblur:1,layer_name:selection
# Prevent blur on msnap screenshot
layerrule = layer_name:msnap, noanim:1, noblur:1

# inspirations (uncomment if needed)
# windowrule=isfloating:1,title:^(open file|save file|choose file)$
# windowrule=width:1200,height:800,title:^(open file|save file|choose file)$
# windowrule=width:1100,height:760,appid:^(1[Pp]assword|com\\.1password\\.1password)$
# windowrule=animation_type_open:none,animation_type_close:none,appid:^flameshot$
# windowrule=noswallow:1,appid:^flameshot$
