default_channel = "files"
global_history  = false
history_size    = 200
tick_rate       = 50

[ui]
  orientation = "landscape"
  theme       = "default"
  ui_scale    = 100

  [ui.input_bar]
    border_type = "rounded"
    position    = "top"
    prompt      = ">"

  [ui.status_bar]
    hidden          = false
    separator_close = ""
    separator_open  = ""

  [ui.results_panel]
    border_type = "rounded"

  [ui.preview_panel]
    border_type = "rounded"
    hidden      = false
    scrollbar   = true
    size        = 65

  [ui.help_panel]
    hidden          = true
    show_categories = true

  [ui.remote_control]
    show_channel_descriptions = true
    sort_alphabetically       = true

[keybindings]
  backspace = "delete_prev_char"
  backtab   = "toggle_selection_up"
  ctrl-a    = "go_to_input_start"
  ctrl-c    = "quit"
  ctrl-down = "select_next_history"
  ctrl-e    = "go_to_input_end"
  ctrl-f    = "cycle_previews"
  ctrl-h    = "toggle_help"
  ctrl-j    = "select_next_entry"
  ctrl-k    = "select_prev_entry"
  ctrl-l    = "toggle_layout"
  ctrl-n    = "select_next_entry"
  ctrl-o    = "toggle_preview"
  ctrl-p    = "select_prev_entry"
  ctrl-r    = "reload_source"
  ctrl-s    = "cycle_sources"
  ctrl-t    = "toggle_remote_control"
  ctrl-u    = "delete_line"
  ctrl-up   = "select_prev_history"
  ctrl-w    = "delete_prev_word"
  ctrl-x    = "toggle_action_picker"
  ctrl-y    = "copy_entry_to_clipboard"
  delete    = "delete_next_char"
  down      = "select_next_entry"
  end       = "go_to_input_end"
  enter     = "confirm_selection"
  esc       = "quit"
  f12       = "toggle_status_bar"
  home      = "go_to_input_start"
  left      = "go_to_prev_char"
  pagedown  = "scroll_preview_half_page_down"
  pageup    = "scroll_preview_half_page_up"
  right     = "go_to_next_char"
  tab       = "toggle_selection_down"
  up        = "select_prev_entry"

[shell_integration]
  fallback_channel = "files"

  [shell_integration.channel_triggers]
    alias = ["alias", "unalias"]
    dirs = ["cd", "ls", "rmdir", "z"]
    env = ["export", "unset"]
    files = [
      "cat",
      "less",
      "head",
      "tail",
      "vim",
      "nano",
      "bat",
      "cp",
      "mv",
      "rm",
      "touch",
      "chmod",
      "chown",
      "ln",
      "tar",
      "zip",
      "unzip",
      "gzip",
      "gunzip",
      "xz",
    ]

  [shell_integration.keybindings]
    command_history    = "ctrl-r"
    smart_autocomplete = "ctrl-t"
